function createConfigFile( directory, folder, fileName, commentString, ...
    time, angle, radius, velo, bgPressure )
%CREATECONFIGFILE Create a configuration file based on model parameters

% Generate file path
FILE_PATH = [directory '\' folder '\' fileName '_' ...
    datestr(now, 'yyyy-mm-dd_HHMM') '.txt'];

% Open file for writing
fileID = fopen(FILE_PATH, 'wt');

% Write information to file
fprintf(fileID, [ ...
    'CONFIGURATION FILE\t' datestr(now, 'yyyy-mm-dd\tHH:MM') '\n\n' ...
    'Temporal limits [s]:\t\t\t'     0 ...
                               ' : ' num2str(max(time) / (numel(time) - 1), 3) ...
                               ' : ' num2str(max(time), 3) '\n' ...
    'Angular limits [deg]:\t\t\t'    num2str(0, 3) ...
                               ' : ' num2str(max(angle) / (numel(angle) - 1), 3) ...
                               ' : ' num2str(max(angle), 3) '\n' ...
    'Radial limits [m]:\t\t\t'       0 ...
                               ' : ' num2str(max(radius) / (numel(radius) - 1), 3) ...
                               ' : ' num2str(max(radius), 3) '\n' ...
    'Velocity limits [m/s]:\t\t\t'   0 ...
                               ' : ' num2str(max(velo) / (numel(velo) - 1), 3) ...
                               ' : ' num2str(max(velo), 3) '\n' ...
    'Background pressue [mbar]:\t\t' num2str(bgPressure, 3) '\n' ...
    '\n\tComments:' '\n' commentString]);

fclose(fileID);
end
